# Generated by Django 6.0.7 on 2026-07-20 08:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_image_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
