# Generated by Django 6.0.7 on 2026-07-23 14:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
