# Generated by Django 6.0.7 on 2026-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_moncabinet_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mc_text1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mc_text2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mc_text3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
