# Generated by Django 6.0.7 on 2026-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_footersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='developed_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Developed by'),
        ),
    ]
