# Generated by Django 6.0.7 on 2026-07-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_footerlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
