# Generated by Django 6.0.7 on 2026-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_socialslogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
    ]
